# Generated by Django 5.1.6 on 2025-03-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('preferred_language', models.CharField(max_length=50)),
                ('source', models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Google', 'Google'), ('Referral', 'Referral'), ('Other', 'Other')], max_length=100, null=True)),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('budget', models.CharField(blank=True, choices=[('10L-50L', '10L-50L'), ('50L-1Cr', '50L-1Cr'), ('1Cr-5Cr', '1Cr-5Cr'), ('5Cr+', '5Cr+')], max_length=50, null=True)),
                ('preferred_locations', models.TextField(blank=True, null=True)),
                ('possession_timeline', models.CharField(blank=True, max_length=50, null=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('voice_recording', models.FileField(blank=True, null=True, upload_to='voice_recordings/')),
                ('transcription', models.TextField(blank=True, null=True)),
                ('key_tags', models.TextField(blank=True, null=True)),
                ('loan_required', models.BooleanField(default=False)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('New Lead', 'New Lead'), ('Follow-up', 'Follow-up'), ('Negotiation', 'Negotiation'), ('Closed', 'Closed'), ('Lost', 'Lost')], default='New Lead', max_length=50)),
                ('objections', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
