# Generated by Django 5.1.6 on 2025-03-05 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('users', '0004_user_current_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='broker',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='users.user'),
            preserve_default=False,
        ),
    ]
