# Generated by Django 5.1.6 on 2025-03-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='extracted_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
