# Generated by Django 5.1.6 on 2025-02-15 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_valid_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='Tell us about yourself, interests, and business motivations')),
                ('professional_summary', models.TextField(help_text='Current role and responsibilities')),
                ('past_roles', models.TextField(help_text='Previous work experience and achievements')),
                ('skills', models.TextField(help_text='Relevant skills and expertise')),
                ('industry_experience', models.TextField(help_text='Relevant industry experience and projects')),
                ('business_idea', models.TextField(help_text='Description of business idea and problem solved')),
                ('market_opportunity', models.TextField(help_text='Target audience and value proposition')),
                ('business_type', models.CharField(choices=[('TECH', 'Technology'), ('PHARMA', 'Pharmaceutical'), ('ECOM', 'E-Commerce'), ('HEALTH', 'Healthcare'), ('FIN', 'Financial Services'), ('EDU', 'Education'), ('RETAIL', 'Retail'), ('FOOD', 'Food & Beverage'), ('CONS', 'Consulting'), ('OTHER', 'Other')], help_text='Primary industry sector of your business', max_length=20)),
                ('target_market', models.CharField(choices=[('B2B', 'Business to Business'), ('B2C', 'Business to Consumer'), ('B2B2C', 'Business to Business to Consumer'), ('B2G', 'Business to Government')], help_text='Primary target market segment', max_length=20)),
                ('technical_proficiency', models.CharField(choices=[('NONE', 'No Technical Background'), ('BASIC', 'Basic Computer Skills'), ('INTERMEDIATE', 'Some Technical Knowledge'), ('ADVANCED', 'Strong Technical Background')], help_text='Technical skill level', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'User Onboarding',
                'verbose_name_plural': 'User Onboardings',
            },
        ),
    ]
