# Generated by Django 5.1.6 on 2025-02-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useronboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_phase',
            field=models.CharField(choices=[('VALIDATION', 'Idea Validation & Research'), ('PLANNING', 'Planning and Strategy Development'), ('EXECUTION', 'Launch & Execution'), ('LEGAL', 'Legal Foundations & Finance'), ('GROWTH', 'Growth Marketing & Scaling')], default='VALIDATION', max_length=50),
        ),
    ]
