# Generated by Django 5.1.6 on 2025-02-15 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_useronboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TODO', 'To Do'), ('INPROGRESS', 'In Progress'), ('REVIEW', 'Under Review'), ('DONE', 'Completed')], max_length=50)),
                ('order', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kanbanboard')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('board', 'name')},
            },
        ),
        migrations.CreateModel(
            name='KanbanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kanbancolumn')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('VALIDATION', 'Idea Validation & Research'), ('PLANNING', 'Planning and Strategy Development'), ('EXECUTION', 'Launch & Execution'), ('LEGAL', 'Legal Foundations & Finance'), ('GROWTH', 'Growth Marketing & Scaling')], max_length=50)),
                ('start_date', models.DateTimeField(null=True)),
                ('completion_date', models.DateTimeField(null=True)),
                ('current_roadmap_index', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'unique_together': {('user', 'phase')},
            },
        ),
        migrations.AddField(
            model_name='kanbanboard',
            name='project_phase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_board', to='core.phaseprogress'),
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='core.phaseprogress')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
