# Generated by Django 5.1.6 on 2025-02-15 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_journal'),
        ('users', '0004_user_current_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phaseprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='users.user'),
        ),
    ]
